import { cn } from "@cn"
import Layout from "@ui/Layout"
import type { Metadata } from "next"
import { DM_Serif_Display, Lexend_Deca } from "next/font/google"
import { ReactNode } from "react"
import "./globals.css"

const sans = Lexend_Deca({
  subsets: ["latin"],
  variable: "--font-lexend-deca"
})
const serif = DM_Serif_Display({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-dm-serif"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

interface IProps {
  children: ReactNode
}

export default function RootLayout({ children }: IProps) {
  return (
    <html lang="en">
      <body className={cn("", sans.variable, serif.variable)}>
        <Layout>{children}</Layout>
      </body>
    </html>
  )
}
